export const LangContent = {
  en: {
    en: 'English',
    pt: 'Portuguese',
    site_description: 'My Site Description',
    blog: 'Blog',
    blog_page_title: 'Blog',
    blog_page_description:
      'Articles about software, tutorials, programming tips, tech',
    about: 'About',
    about_page_title: 'About Me',
    about_page_description: 'Some words about me and contact form',
    hero_name: 'John Doe',
    hero_name_role: 'FullStack Developer & Engineering Manager',
    hero_name_description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. At repudiandae id repellendus maxime architecto inventore esse rerum nobis, consectetur, laborum veniam neque, deleniti obcaecati doloremque amet temporibus magni et quod.',
    blog_description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque atexplicabo quia odit. Numquam nemo qui cupiditate.',
    blog_search_placeholder: 'Search articles by title, excerpt or tag',
    copyright: 'All rights reserved',
    no_posts_found: 'No posts found.',
    latest_posts: 'Latest Posts',
    all_posts: 'All Posts',
    posted_by: 'Posted by',
    on: 'on',
    view: 'view',
    views: 'views',
    no_views: 'no_views',
    like: 'like',
    likes: 'likes',
    no_likes: 'no_likes',
    btn_like_text: 'Like',
    article_in: 'Article in',
    about_description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi accusantium dignissimos similique totam voluptatum molestias dolor mollitia tempora nihil odio molestiae harum incidunt corporis esse quasi pariatur, voluptatem cupiditate ea.',
    contact_me: 'Contact Me',
    cannot_be_empty: 'Cannot be empty, please fill the field',
    invalid_email_format: 'Invalid email format',
    from: 'Name',
    email: 'Email',
    message: 'Message',
    submit: 'Send',
    message_sent: 'Message sent!',
    message_not_sent: 'There was a problem, please try again!',
    share_on: 'Share on',
    save_on: 'Save on'
  },
  pt: {
    en: 'Inglês',
    pt: 'Português',
    site_description: 'Descrição Site',
    blog: 'Blog',
    blog_page_title: 'Blog',
    blog_page_description:
      'Artigos sobre software, tutoriais, dicas programação, tecnologia',
    about: 'Acerca',
    about_page_title: 'Acerca de mim',
    about_page_description:
      'Algumas palavras sobre mim e formulário de contacto',
    hero_name: 'John Doe',
    hero_name_role: 'FullStack Developer & Engineering Manager',
    hero_name_description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. At repudiandae id repellendus maxime architecto inventore esse rerum nobis, consectetur, laborum veniam neque, deleniti obcaecati doloremque amet temporibus magni et quod.',
    blog_description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque atexplicabo quia odit. Numquam nemo qui cupiditate.',
    blog_search_placeholder: 'Procurar artigos por titulo, descrição ou tags',
    copyright: 'Todos os direitos reservados',
    no_posts_found: 'Não foram encontrados artigos.',
    latest_posts: 'Últimos Artigos',
    all_posts: 'Todos os Artigos',
    posted_by: 'Publicado por',
    on: 'em',
    view: 'visualização',
    views: 'visualizações',
    no_views: 'sem visualizações',
    like: 'gosto',
    likes: 'gostos',
    no_likes: 'sem gostos',
    btn_like_text: 'Gosto',
    article_in: 'Artigo em',
    about_description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi accusantium dignissimos similique totam voluptatum molestias dolor mollitia tempora nihil odio molestiae harum incidunt corporis esse quasi pariatur, voluptatem cupiditate ea.',
    contact_me: 'Contacte-me',
    cannot_be_empty: 'Campo vazio, por favor preencha',
    invalid_email_format: 'Formato de email inválido',
    from: 'Nome',
    email: 'Email',
    message: 'Mensagem',
    submit: 'Enviar',
    message_sent: 'Mensagem enviada!',
    message_not_sent: 'Houve um problema, por favor tente de novo!',
    share_on: 'Partilha no',
    save_on: 'Guarda no'
  }
};
